name: Build, Push, and Deploy to GCP Cloud Run
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: solana-spl-trader
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-east1-docker.pkg.dev
    - name: Build Docker Image
      run: |
        docker build -f Dockerfile -t us-east1-docker.pkg.dev/solana-spl-trader/spl-trader/spl-seller:latest .
    - name: Push Docker Image to Artifact Registry
      run: |
        docker push us-east1-docker.pkg.dev/solana-spl-trader/spl-trader/spl-seller:latest
    - name: Deploy Seller to Cloud Run
      run: |
        gcloud run deploy spl-seller-service \
          --image us-east1-docker.pkg.dev/solana-spl-trader/spl-trader/spl-seller:latest \
          --platform managed \
          --region us-east1 \
          --allow-unauthenticated \
          --min-instances 1 \
          --max-instances 1 \
          --set-env-vars HELIUS_API_KEY=${{ secrets.HELIUS_API_KEY }},BIRDEYE_API_TOKEN=${{ secrets.BIRDEYE_API_TOKEN }},SOLANA_PRIVATE_KEY1=${{ secrets.SOLANA_PRIVATE_KEY1 }},SOLANA_PRIVATE_KEY2=${{ secrets.SOLANA_PRIVATE_KEY2 }},SOLANA_PRIVATE_KEY3=${{ secrets.SOLANA_PRIVATE_KEY3 }},PV_EXIT_INDEX1=${{ secrets.PV_EXIT_INDEX1 }},PV_EXIT_INDEX2=${{ secrets.PV_EXIT_INDEX2 }},PV_EXIT_INDEX3=${{ secrets.PV_EXIT_INDEX3 }},MODE=SELLER
